// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBHhNs6Zc17xMtuxf-Z7RErX_JGocCiJTo',
    appId: '1:387662996338:web:3e75628a7fa26bd463b3eb',
    messagingSenderId: '387662996338',
    projectId: 'app-de-servicios-flutter',
    authDomain: 'app-de-servicios-flutter.firebaseapp.com',
    storageBucket: 'app-de-servicios-flutter.appspot.com',
    measurementId: 'G-79MCNVSKJX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCedw8rUaHl0WnohiDTTXWsTAFaOMWfn8Y',
    appId: '1:387662996338:android:4b2cb101f2a1334363b3eb',
    messagingSenderId: '387662996338',
    projectId: 'app-de-servicios-flutter',
    storageBucket: 'app-de-servicios-flutter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD3yUza3tf08l5qL0e31ePF-O0VCLzPy1o',
    appId: '1:387662996338:ios:5ca7dae65c4cceef63b3eb',
    messagingSenderId: '387662996338',
    projectId: 'app-de-servicios-flutter',
    storageBucket: 'app-de-servicios-flutter.appspot.com',
    iosBundleId: 'com.example.serviciosApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD3yUza3tf08l5qL0e31ePF-O0VCLzPy1o',
    appId: '1:387662996338:ios:5ca7dae65c4cceef63b3eb',
    messagingSenderId: '387662996338',
    projectId: 'app-de-servicios-flutter',
    storageBucket: 'app-de-servicios-flutter.appspot.com',
    iosBundleId: 'com.example.serviciosApp',
  );
}
